#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8081
#spring:
#  application:
#    name: TheaterMicroservice
#  datasource:
#    url: jdbc:mysql://localhost:3306/movie
#    username: root
#    password: pass@word1
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true